name: build
on:
  push:
    branches: [main, dev]
  workflow_dispatch: ~

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get branch
        run: |
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
          TAG=${GITHUB_REF##*/}
          if [ "$TAG" == "main" ] ; then TAG=latest ; fi
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: docker build
        run: docker build -t acdhch/nestify-base-app:$TAG --label "buildUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" .
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker push
        run: docker push acdhch/nestify-base-app:$TAG
      - name: redeploy
        run: |
          NMSP=wks-dev
          if [ "$TAG" == "latest" ] ; then NMSP=wks-dev ; fi
          echo "https://rancher.acdh-dev.oeaw.ac.at/v3/project/c-m-6hwgqq2g:p-6r7ql/workload/deployment:$NMSP:nestify?action=redeploy"
          curl -i -X POST -H "Authorization: Bearer ${{ secrets.RANCHER_TOKEN }}" "https://rancher.acdh-dev.oeaw.ac.at/v3/project/c-m-6hwgqq2g:p-6r7ql/workload/deployment:$NMSP:nestify?action=redeploy"